<!-- start middle -->
<div class="middle">
    <!-- start inner -->
    <div class="inner">
        <!--  []  -->
        <div class="full-width">
            <div class="two-third">
                <h1><?php echo $this->translate("Cadastro"); ?></h1>
                <h4 class="mb20"><?php echo $this->translate("Validar cadastro"); ?></h4>
                <p><?php echo $this->translate("Para completar o seu cadastro, precisamos confirmar a veracidade da sua conta."); ?></p>
                <p><?php echo $this->translate("Para isso enviamos um email para <strong>"); ?><?php echo $this->email; ?> <?php echo $this->translate("</strong>contendo um link para confirmar sua conta."); ?></p>
            </div>
        </div>
    </div>
</div>



