<div class="middle">
    <!-- start inner -->
    <div class="inner">
        <!--  []  -->
        <div class="full-width">
            <div class="two-third">
                <h1><?php echo $this->translate("Confirmação de cadastro"); ?></h1>
                <h4 class="mb20"><?php echo $this->translate("Aguardando confirmação do endereço de email."); ?></h4>
                <p>
                    <?php echo $this->translate($this->msg); ?>  
                </p>    

            </div>
        </div>
    </div>
</div>