<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
    <head profile="http://gmpg.org/xfn/11">

        <title>Regallo - Gerenciador Financeiro</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <!--        <meta name="keywords" content="Asteroid, XHTML, HTML, Theme, Template" />-->
        <meta name="description" content="Asteroid" />

        <link rel="shortcut icon" href="<?php echo $this->baseUrl("images/icons/favicon.ico"); ?>" type="image/x-icon" />


        <style type="text/css" media="all">
            @import url("http://fonts.googleapis.com/css?family=Lato:400,700,400italic|PT+Sans+Narrow:400,700");

            @import url("js/jwysiwyg/jquery.wysiwyg.css");
            @import url("js/fancybox/jquery.fancybox-1.3.4.css");
            @import url("js/jdpicker/jdpicker.css");
            @import url("js/visualize/css/visualize.css");
            @import url("js/fullcalendar/fullcalendar.css");
            @import url("css/datatable.css");

            @import url("css/style.css");

            @import url("css/crimson-orange.css");
            @import url("css/soft-blue.css");
            @import url("css/soft-red.css");
            @import url("css/soft-purple.css");
            @import url("css/soft-yellow.css");
            @import url("css/blue-gray.css");
        </style>

        <!--[if IE]>
                        <link rel="stylesheet" type="text/css" href="css/ie.css" />
                <![endif]-->

        <!-- Icons -->
        <link href="ico/favicon.ico" rel="icon" type="image/ico" />
        <link href="ico/favicon.ico" rel="shortcut icon" type="image/ico" />
        <link href="ico/speed-dial.png" rel="apple-touch-icon" type="image/png" />
        <link href="ico/speed-dial.png" rel="icon" type="image/png" />
        <link href="ico/apple-touch-icon-precomposed.png" rel="apple-touch-icon-precomposed" type="image/png" />



        <script type="text/javascript" src="js/jquery-1.6.4.min.js"></script>
        <script type="text/javascript" src="js/wrappers.js"></script>


        <script type="text/javascript" src="js/jquery-ui-1.8.16.custom.min.js"></script>
        <script type="text/javascript" src="js/jquery.uniform/jquery.uniform.min.js"></script>
        <script type="text/javascript" src="js/jquery-css-transform.js"></script>
        <script type="text/javascript" src="js/rotate3Di.js"></script>
        <script type="text/javascript" src="js/jwysiwyg/jquery.wysiwyg.js"></script>
        <script type="text/javascript" src="js/jdpicker/jquery.jdpicker.js"></script>
        <script type="text/javascript" src="js/jquery.hotkeys.js"></script>
        <script type="text/javascript" src="js/tap-or-click.js"></script>
        <script type="text/javascript" src="js/jquery.datatable/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="js/jquery-validation-1.8.1/jquery.validate.min.js"></script>
        <script type="text/javascript" src="js/jquery.detectmobilebrowser.js"></script>

        <!--[if IE]>
                <script type="text/javascript" src="js/excanvas.js"></script>
        <![endif]-->

        <script type="text/javascript" src="js/visualize/visualize.jQuery.js"></script>
        <script type="text/javascript" src="js/visualize/jquery.visualize.tooltip.js"></script>
        <script type="text/javascript" src="js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>

        <script type="text/javascript" src="js/fullcalendar/fullcalendar.min.js"></script>

        <script type="text/javascript" src="js/main.js"></script>



        <?php echo $this->headScript() ?>
        <?php echo $this->headLink() ?>


    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>