



<div class="column grid-5">

    <div class="block small">

        <div class="top">
            <h2>Ações</h2>

            <ul>
                <li><a href="">Find all items</a></li>
                <li><a href="">Sort items</a></li>
            </ul>
        </div>

        <div class="content">

            <ul class="menu">
                <li><a href="">Link number 1</a></li>
                <li><a href="" class="selected">Link number 2</a></li>
                <li><a href="">Link number 3</a></li>
                <li><a href="">Link number 4</a></li>
            </ul>

        </div>

    </div>

</div>
<div class="column grid-11">

    <div class="block small">

        <div class="top">
            <h2>Recebimentos agendados para esta semana</h2>
        </div>

        <div class="content">
            Mostrar aqui

        </div> <!-- End Block Content -->

    </div> <!-- End Block -->

    

</div> <!-- End Column -->

<div class="clear">&nbsp;</div>