<?php echo $this->headScript()->appendFile($this->baseUrl("js/modules/default/produtos/form.js")); ?>
<div class="column grid-16">
    <div class="block">
        <div class="top">
            <h2>Produtos / Cadastrar</h2>
            <ul>
                <li><a href="<?php echo $this->url(array("controller"=>"produtos","action"=>"index"),null,true) ?>">Voltar a lista</a></li>
            </ul>
        </div>
        <div class="content">
            
            <form action="<?php echo $this->url(array("controller" => "produtos", "action" => "salvar")); ?>" method="post" enctype="multipart/form-data">
                <input type="hidden" name="produto[id]" value="" />

                <fieldset>
                    <legend>Dados do produto</legend>

                    <p>
                        <label><input type="checkbox" name="produto[ativo]" value="1" checked="checked"/>Ativo</label><br/>
                    </p>

                    <p>
                        <label>Código</label><br/>
                        <input class="text small" type="text" value="<?php echo $this->produto->cod; ?>" name="produto[cod]"/>
                        <small>COD. ex: BP001</small>
                    </p>

                    <p>
                        <label>Nome</label> <small class="above">Escreva o nome do produto</small><br/>
                        <input class="text big" type="text" value="<?php echo $this->produto->nome; ?>" name="produto[nome]"/>
                    </p>

                    <p>
                        <label>Categoria</label> <br/>
                        <select name="produto[categoria_id]">
                            <?php foreach($this->categorias as $c): ?>
                            <?php $check = "" ?>
                            <option value="<?php echo $c->id; ?>"><?php echo $c->nome; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </p>

                    <p>
                        <label>Foto</label> <br/>
                        <input type="file" name="file"/>
                    </p>

                    <p>
                        <label>Descrição</label> <br/>
                        <textarea name="produto[descricao]" rows="10" cols="80"></textarea>
                    </p>

                </fieldset>
                <fieldset>
                    <legend>Dados financeiros</legend>

                    <p>
                        <label>Quantidade em estoque</label><br/>
                        <input class="text small" type="text" value="" name="produto[estoque]"/>
                    </p>

                    <p>
                        <label>Valor de custo</label><br/>
                        <input id="produto_valor_custo" class="text small" type="text" value="" name="produto[valor_custo]"/>
                    </p>

                    <p>
                        <label>Valor de venda</label><br/>
                        <input id="produto_valor_venda" class="text small" type="text" value="" name="produto[valor_venda]"/>
                    </p>

                    <p>
                        <input type="submit" value="Salvar" />
                    </p>

                </fieldset>
            </form>
        </div>

    </div>
</div>