<div class="column grid-16">
    <div class="block">
        <div class="top">
            <h2>Vender</h2>

        </div>
        <div class="content">
            <form action="<?php echo $this->url(array("controller" => "vender", "action" => "salvarPedido")); ?>" method="post" enctype="multipart/form-data">
                <!--                <fieldset>-->
                <!--                    <legend>Escolha o cliente</legend>
                                </fieldset>-->
                <p>
                    <label>Selecione o cliente</label><br/>
                    <select name="registro[cliente_id]">
                        <?php foreach ($this->clientes as $c): ?>
                            <option value="<?php echo $c->id ?>"><?php echo $c->nome ?></option>
                        <?php endforeach; ?>
                    </select>


                </p>

                <fieldset>
                    <legend>Produtos</legend>
                    <ul class="image-list" rel="sortable_result">
                        <?php for($i=0;$i<10;$i++): ?>
                        <li id="Image1">
                            <a href="img/_photo.jpg" class="fancybox"><img src="img/_thumb.jpg" alt="thumb"/></a>
                            <span class="move">&nbsp;</span>
                            <ul>
                                <li class="edit"><a href="#">Alterar</a></li>
                                <li class="delete"><a class="delete" href="#">Deletar</a></li>
                            </ul>
                        </li>
                        <?php endfor; ?>

                    </ul>
                </fieldset>

                <fieldset>
                    <legend>Forma de pagamento</legend>
                </fieldset>

            </form>
        </div>

    </div>
</div>