<div class="parcela">
    <p>
        <label>Data:</label><br/>
        <input class="date" name="parcelas[<?php echo $this->parcela ?>][data]" type="text" style="width: 150px;" />
    </p>
    <p>
        <label>Tipo pagamento</label><br/>
        <label><input type="radio" name="parcelas[<?php echo $this->parcela; ?>][tipo_pagamento]" value="dinheiro" /> Dinheiro</label>
        <label><input type="radio" name="parcelas[<?php echo $this->parcela; ?>][tipo_pagamento]" value="cheque" /> Cheque</label>
        <label><input type="radio" name="parcelas[<?php echo $this->parcela; ?>][tipo_pagamento]"  value="promissoria" /> Dinheiro</label>
    </p>
    <p>
        <label>Valor desta parcela:</label><br/>
        <input type="text" name="parcelas[<?php echo $this->parcela; ?>][valor]" class="moeda" style="width: 190px;" />
    </p>
    <p>
        <label>Foi pago? </label>
        <input type="checkbox" value="1" name="parcelas[<?php echo $this->parcela; ?>][paga]" /><br/>
        <input type="button" class="deletar_parcela" value="remover parcela" />
    </p>
    
</div>